import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useState } from 'react'
import api from '../../services/api'

export function ChatbotPage() { const [message, setMessage] = useState(''); const [answer, setAnswer] = useState(''); const ask = useMutation({ mutationFn: async () => (await api.post('/chat', { message })).data, onSuccess: data => setAnswer(data.answer) }); return <div className="mx-auto max-w-3xl"><h1 className="text-3xl font-bold">AI assistant</h1><p className="mt-2 text-slate-500">Ask about complaint status, pending work, and campus trends.</p><form onSubmit={e => { e.preventDefault(); if (message.trim()) ask.mutate() }} className="mt-7 flex gap-2"><input value={message} onChange={e => setMessage(e.target.value)} className="flex-1 rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm dark:border-slate-700 dark:bg-slate-900" placeholder="Show my pending complaints"/><button className="rounded-xl bg-brand-600 px-5 text-sm font-semibold text-white">Ask</button></form>{answer && <section className="mt-5 rounded-2xl border border-brand-100 bg-brand-50 p-5 leading-7 dark:border-brand-500/20 dark:bg-brand-500/10">{answer}</section>}</div> }

export function SlaPage() { const client = useQueryClient(); const { data = [] } = useQuery({ queryKey: ['sla'], queryFn: async () => (await api.get('/sla')).data }); const check = useMutation({ mutationFn: () => api.post('/sla/process-expired'), onSuccess: () => client.invalidateQueries({ queryKey: ['sla'] }) }); return <div><div className="flex items-end justify-between"><div><h1 className="text-3xl font-bold">SLA dashboard</h1><p className="mt-2 text-slate-500">Due times and escalation status.</p></div><button onClick={() => check.mutate()} className="rounded-xl bg-brand-600 px-4 py-2.5 text-sm font-semibold text-white">Check expired</button></div><div className="mt-7 space-y-3">{data.map((item: any) => <div key={item.id} className="flex items-center justify-between rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><div><p className="font-mono text-xs text-brand-600">{item.ticketId}</p><p className="mt-1 font-semibold">{item.department}</p></div><p className={item.expired ? 'font-semibold text-rose-600' : 'text-sm text-slate-500'}>{item.expired ? 'Expired' : `${item.remainingHours} hours remaining`}</p></div>)}</div></div> }

export function HeatmapPage() { const { data = [] } = useQuery({ queryKey: ['heatmap'], queryFn: async () => (await api.get('/heatmap')).data }); return <div><h1 className="text-3xl font-bold">Campus heatmap</h1><div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{data.map((item: any) => <article key={item.location} className={`rounded-2xl p-6 ${item.level === 'red' ? 'bg-rose-100 text-rose-900 dark:bg-rose-950 dark:text-rose-100' : item.level === 'yellow' ? 'bg-amber-100 text-amber-900 dark:bg-amber-950 dark:text-amber-100' : 'bg-emerald-100 text-emerald-900 dark:bg-emerald-950 dark:text-emerald-100'}`}><p className="font-bold">{item.location}</p><p className="mt-3 text-3xl font-bold">{item.complaintCount}</p><p className="mt-1 text-sm">complaints · {item.criticalCount} critical</p></article>)}</div></div> }

export function RecommendationsPage() { const { data = [] } = useQuery({ queryKey: ['recommendations'], queryFn: async () => (await api.get('/recommendations')).data }); return <div><h1 className="text-3xl font-bold">AI recommendations</h1><div className="mt-7 space-y-4">{data.map((item: any, index: number) => <article key={index} className="rounded-2xl border border-slate-200 bg-white p-6 dark:border-slate-800 dark:bg-slate-900"><p className="font-bold">{item.location} · {item.category}</p><p className="mt-3 leading-6">{item.recommendation}</p></article>)}</div></div> }
