import { BuildingOffice2Icon, CheckCircleIcon, ClockIcon, UserGroupIcon } from '@heroicons/react/24/outline'
import { useQuery } from '@tanstack/react-query'
import { Link } from 'react-router-dom'
import SimpleBarChart from '../../components/administration/SimpleBarChart'
import ComplaintTable from '../../components/complaints/ComplaintTable'
import StatCard from '../../components/complaints/StatCard'
import { administrationService } from '../../services/administration'

export default function AdminDashboardPage() { const { data, isLoading } = useQuery({ queryKey: ['admin-analytics'], queryFn: administrationService.analytics }); if (isLoading) return <div className="rounded-2xl bg-white p-12 text-center text-slate-500 dark:bg-slate-900">Loading your operations overview...</div>; const totals = data?.totals; return <div><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold text-brand-600">Administration</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Operations overview</h1><p className="mt-2 text-slate-500 dark:text-slate-400">A live view of grievance operations across the institution.</p></div><Link to="/admin/complaints" className="rounded-xl bg-brand-600 px-4 py-2.5 text-center text-sm font-semibold text-white hover:bg-brand-700">Review complaints</Link></div><div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Total complaints" value={totals?.totalComplaints ?? 0} icon={<ClockIcon className="h-6 w-6" />} /><StatCard label="Resolved" value={totals?.resolved ?? 0} icon={<CheckCircleIcon className="h-6 w-6" />} accent="text-emerald-600 bg-emerald-50 dark:bg-emerald-500/10" /><StatCard label="Departments" value={totals?.departments ?? 0} icon={<BuildingOffice2Icon className="h-6 w-6" />} accent="text-violet-600 bg-violet-50 dark:bg-violet-500/10" /><StatCard label="Staff accounts" value={totals?.staff ?? 0} icon={<UserGroupIcon className="h-6 w-6" />} accent="text-sky-600 bg-sky-50 dark:bg-sky-500/10" /></div><div className="mt-8 grid gap-6 xl:grid-cols-2"><SimpleBarChart title="Complaint trend" data={data?.monthly ?? []} /><SimpleBarChart title="Department performance" data={data?.topDepartments ?? []} color="bg-violet-500" /></div><div className="mt-8"><div className="mb-4 flex items-center justify-between"><div><h2 className="text-lg font-bold">Recent complaints</h2><p className="text-sm text-slate-500">Latest submissions across all departments.</p></div><Link to="/admin/analytics" className="text-sm font-semibold text-brand-600">Open analytics</Link></div><ComplaintTable complaints={data?.recentComplaints ?? []} role="admin" showStudent /></div></div> }
