import { ArrowPathIcon, CpuChipIcon } from '@heroicons/react/24/outline'
import type { Complaint } from '../../types/complaint'

const sentimentClass: Record<string, string> = { Positive: 'bg-emerald-100 text-emerald-700', Neutral: 'bg-slate-100 text-slate-700', Negative: 'bg-rose-100 text-rose-700', Frustrated: 'bg-amber-100 text-amber-700', Urgent: 'bg-orange-100 text-orange-700' }

export default function AIInsightsPanel({ complaint, canReprocess, isReprocessing, onReprocess }: { complaint: Complaint; canReprocess: boolean; isReprocessing: boolean; onReprocess: () => void }) {
  const rows = [['Detected language', complaint.originalLanguage], ['Category', complaint.category], ['Suggested department', complaint.predictedDepartment || complaint.aiDepartment], ['Predicted priority', complaint.predictedPriority], ['Confidence', `${complaint.confidence}%`], ['Duplicate check', complaint.duplicate ? `${Math.round(complaint.similarityScore * 100)}% similar` : 'No likely duplicate']]
  return <section className="rounded-2xl border border-brand-100 bg-gradient-to-br from-brand-50 to-white p-6 shadow-sm dark:border-brand-500/20 dark:from-brand-500/10 dark:to-slate-900"><div className="flex flex-wrap items-start justify-between gap-3"><div className="flex gap-3"><div className="rounded-xl bg-brand-600 p-2.5 text-white"><CpuChipIcon className="h-5 w-5" /></div><div><h2 className="font-bold">AI complaint insights</h2><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">{complaint.aiStatus === 'completed' ? `Processed by ${complaint.aiVersion}` : 'AI processing is pending. Reprocess after configuring Groq.'}</p></div></div>{canReprocess && <button disabled={isReprocessing} onClick={onReprocess} className="inline-flex items-center gap-2 rounded-xl border border-brand-200 bg-white px-3 py-2 text-sm font-semibold text-brand-700 hover:bg-brand-50 disabled:opacity-60 dark:border-brand-500/30 dark:bg-slate-900 dark:text-brand-300"><ArrowPathIcon className={`h-4 w-4 ${isReprocessing ? 'animate-spin' : ''}`} />Reprocess</button>}</div><div className="mt-5 grid gap-3 sm:grid-cols-2">{rows.map(([label, value]) => <div key={label} className="rounded-xl bg-white/80 p-3 dark:bg-slate-900/70"><p className="text-xs font-medium text-slate-500">{label}</p><p className="mt-1 text-sm font-semibold">{value}</p></div>)}</div><div className="mt-4 rounded-xl bg-white/80 p-4 dark:bg-slate-900/70"><p className="text-xs font-medium text-slate-500">English translation</p><p className="mt-1 text-sm leading-6">{complaint.translatedText || complaint.description}</p></div><div className="mt-3 rounded-xl bg-white/80 p-4 dark:bg-slate-900/70"><p className="text-xs font-medium text-slate-500">AI explanation</p><p className="mt-1 text-sm leading-6">{complaint.aiExplanation || 'Explanation will be available after AI processing.'}</p>{complaint.duplicate && <p className="mt-2 text-xs font-medium text-amber-700 dark:text-amber-300">{complaint.suggestedAction}</p>}</div><div className="mt-3 flex flex-wrap items-center gap-2"><span className="rounded-full bg-brand-100 px-2.5 py-1 text-xs font-semibold text-brand-700 dark:bg-brand-500/15 dark:text-brand-300">{complaint.summary || complaint.title}</span><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${sentimentClass[complaint.sentiment] ?? sentimentClass.Neutral}`}>{complaint.sentiment}</span></div></section>
}
