import { ArrowRightIcon, SparklesIcon } from '@heroicons/react/24/outline'
import { Link } from 'react-router-dom'
import type { Complaint } from '../../types/complaint'
import { PriorityBadge, StatusBadge } from './Badges'

export default function ComplaintTable({ complaints, role, showStudent = false }: { complaints: Complaint[]; role: string; showStudent?: boolean }) {
  if (!complaints.length) return <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-12 text-center text-sm text-slate-500 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-400">No complaints match this view yet.</div>
  return <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900"><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500 dark:bg-slate-800/70 dark:text-slate-400"><tr><th className="px-5 py-3">Ticket</th><th className="px-5 py-3">Complaint</th>{showStudent && <th className="px-5 py-3">Student</th>}<th className="px-5 py-3">Department</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Priority</th><th className="px-5 py-3" /></tr></thead><tbody className="divide-y divide-slate-100 dark:divide-slate-800">{complaints.map((item) => <tr key={item.id} className="hover:bg-slate-50/80 dark:hover:bg-slate-800/40"><td className="whitespace-nowrap px-5 py-4 font-mono text-xs text-brand-600">{item.ticketId}</td><td className="max-w-xs px-5 py-4"><p className="truncate font-semibold text-slate-900 dark:text-white">{item.title}</p><p className="mt-1 flex items-center gap-1 truncate text-xs text-slate-500"><SparklesIcon className="h-3 w-3 text-brand-500" />{item.summary || new Date(item.updatedAt).toLocaleDateString()}</p></td>{showStudent && <td className="whitespace-nowrap px-5 py-4 text-slate-600 dark:text-slate-300">{item.studentName}</td>}<td className="whitespace-nowrap px-5 py-4 text-slate-600 dark:text-slate-300">{item.predictedDepartment || item.department}</td><td className="whitespace-nowrap px-5 py-4"><StatusBadge status={item.status} /></td><td className="whitespace-nowrap px-5 py-4"><PriorityBadge priority={item.predictedPriority || item.priority} /></td><td className="px-5 py-4"><Link className="inline-flex items-center gap-1 font-semibold text-brand-600 hover:text-brand-700" to={`/${role}/complaints/${item.id}`}>View <ArrowRightIcon className="h-4 w-4" /></Link></td></tr>)}</tbody></table></div></div>
}
